FROM node:18 as builder

WORKDIR /musiclocal

COPY common/ ./common/
COPY ui/ ./ui/
RUN cd ui && yarn && yarn build

FROM nginx
COPY ./ui/musiclocal-ui.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /musiclocal/ui/dist /usr/share/nginx/musiclocal

EXPOSE 80