name: Build & Upload

on:
  push:
    branches: [ main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push UI
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile_ui
          tags: andreiserban24/musiclocalui:latest
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push Server
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile_server
          tags: andreiserban24/musiclocalserver:latest
          platforms: linux/amd64,linux/arm64
