name: Build & Upload

on: 
  push:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Resolve dependencies
        run: |
          sudo apt-get install -y libasound2-dev

      - name: Install 
        run: |
          cd server
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          yarn
          yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: |
            server/dist

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          cd ui
          yarn
          yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ui
          path: |
            ui/dist
