name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UI
        run: |
          cd ui
          yarn

      - name: Lint UI
        run: |
          cd ui
          yarn lint-ci

      - name: Prettier UI
        run: |
          cd ui
          yarn prettier-ci
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Server
        run: |
          cd server
          yarn

      - name: Lint Server
        run: |
          cd server
          yarn lint-ci

      - name: Prettier Server
        run: |
          cd server
          yarn prettier-ci