name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint UI
        run: |
          cd ui
          yarn
          yarn lint-ci
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Server
        run: |
          cd server
          yarn
          yarn lint-ci